// Demo data for GitHub Pages deployment
// When API is unavailable, the app shows this realistic sample data

export const DEMO_MODE = window.location.hostname.includes('github.io')

export const demoMetricsSummary = {
  total_documents: 247,
  total_processed: 231,
  total_failed: 8,
  total_pending: 8,
  avg_confidence: 0.847,
  avg_processing_time: 2.3,
  models_registered: 4,
  taxonomy_tags: 27,
  total_matters: 12,
}

export const demoMatters = [
  {
    id: '1',
    name: 'Acme Corp Acquisition',
    matter_type: 'M&A / Corporate',
    document_count: 45,
    completed_count: 42,
    failed_count: 1,
    pending_count: 2,
    created_at: '2025-12-15T10:30:00Z',
    avg_confidence: 0.89,
  },
  {
    id: '2',
    name: 'Series B Funding Round',
    matter_type: 'Investment Funds',
    document_count: 28,
    completed_count: 28,
    failed_count: 0,
    pending_count: 0,
    created_at: '2025-12-10T14:20:00Z',
    avg_confidence: 0.92,
  },
  {
    id: '3',
    name: 'Smith v. Johnson Settlement',
    matter_type: 'Litigation',
    document_count: 67,
    completed_count: 65,
    failed_count: 2,
    pending_count: 0,
    created_at: '2025-12-08T09:15:00Z',
    avg_confidence: 0.85,
  },
  {
    id: '4',
    name: 'Office Lease - 123 Main St',
    matter_type: 'Real Estate',
    document_count: 15,
    completed_count: 15,
    failed_count: 0,
    pending_count: 0,
    created_at: '2025-12-05T16:45:00Z',
    avg_confidence: 0.91,
  },
  {
    id: '5',
    name: 'IPO Registration',
    matter_type: 'Securities / Capital Markets',
    document_count: 34,
    completed_count: 30,
    failed_count: 1,
    pending_count: 3,
    created_at: '2025-12-01T11:00:00Z',
    avg_confidence: 0.88,
  },
  {
    id: '6',
    name: 'Executive Employment Agreements',
    matter_type: 'Employment',
    document_count: 12,
    completed_count: 12,
    failed_count: 0,
    pending_count: 0,
    created_at: '2025-11-28T13:30:00Z',
    avg_confidence: 0.94,
  },
]

export const demoDocuments = [
  {
    id: '101',
    filename: 'Merger_Agreement_Draft_v3.pdf',
    status: 'completed',
    matter_id: '1',
    matter_name: 'Acme Corp Acquisition',
    page_count: 45,
    word_count: 12450,
    uploaded_at: '2025-12-20T10:30:00Z',
    processed_at: '2025-12-20T10:32:15Z',
  },
  {
    id: '102',
    filename: 'Due_Diligence_Report.pdf',
    status: 'completed',
    matter_id: '1',
    matter_name: 'Acme Corp Acquisition',
    page_count: 128,
    word_count: 45000,
    uploaded_at: '2025-12-19T14:20:00Z',
    processed_at: '2025-12-19T14:28:45Z',
  },
  {
    id: '103',
    filename: 'LP_Agreement_Final.pdf',
    status: 'completed',
    matter_id: '2',
    matter_name: 'Series B Funding Round',
    page_count: 32,
    word_count: 8900,
    uploaded_at: '2025-12-18T09:15:00Z',
    processed_at: '2025-12-18T09:17:30Z',
  },
  {
    id: '104',
    filename: 'Settlement_Agreement.pdf',
    status: 'completed',
    matter_id: '3',
    matter_name: 'Smith v. Johnson Settlement',
    page_count: 18,
    word_count: 5200,
    uploaded_at: '2025-12-17T16:45:00Z',
    processed_at: '2025-12-17T16:47:00Z',
  },
  {
    id: '105',
    filename: 'Complaint_Filed.pdf',
    status: 'processing',
    matter_id: '3',
    matter_name: 'Smith v. Johnson Settlement',
    page_count: 24,
    word_count: 7100,
    uploaded_at: '2025-12-26T11:00:00Z',
    processed_at: null,
  },
]

export const demoModels = [
  {
    id: 'm1',
    name: 'pile-of-law/legalbert-large-1.7M-2',
    type: 'semantic',
    description: 'LegalBERT trained on 256GB of legal text from Pile of Law. Optimized for legal document understanding and classification.',
    huggingface_url: 'https://huggingface.co/pile-of-law/legalbert-large-1.7M-2',
    size_gb: 1.35,
    approved: true,
    approved_by: 'admin',
    approved_at: '2025-12-01T10:00:00Z',
    created_at: '2025-12-01T09:00:00Z',
    usage_count: 231,
  },
  {
    id: 'm2',
    name: 'surya-ocr',
    type: 'ocr',
    description: 'High-accuracy OCR model with GPU acceleration. Supports MPS (Apple Silicon) and CUDA. Provides word-level bounding boxes.',
    huggingface_url: 'https://github.com/VikParuchuri/surya',
    size_gb: 0.8,
    approved: true,
    approved_by: 'admin',
    approved_at: '2025-12-15T14:00:00Z',
    created_at: '2025-12-15T13:00:00Z',
    usage_count: 45,
  },
  {
    id: 'm3',
    name: 'gemini-2.0-flash',
    type: 'llm',
    description: 'Google Gemini 2.0 Flash for intelligent zone detection and document analysis. Used for smart pipeline routing.',
    huggingface_url: null,
    size_gb: null,
    approved: true,
    approved_by: 'admin',
    approved_at: '2025-12-10T16:00:00Z',
    created_at: '2025-12-10T15:00:00Z',
    usage_count: 89,
  },
  {
    id: 'm4',
    name: 'microsoft/Florence-2-base',
    type: 'vision',
    description: 'Vision-language model for charts, tables, and figures. Extracts structured data from visual elements.',
    huggingface_url: 'https://huggingface.co/microsoft/Florence-2-base',
    size_gb: 0.5,
    approved: false,
    approved_by: null,
    approved_at: null,
    created_at: '2025-12-20T10:00:00Z',
    usage_count: 0,
  },
]

export const demoTaxonomy = [
  {
    id: 't1',
    name: 'M&A / Corporate',
    description: 'Mergers, acquisitions, and corporate transactions',
    color: '#8b5cf6',
    icon: 'Building2',
    tag_count: 3,
    tags: [
      { id: 'tag1', name: 'Merger Agreement', description: 'Merger and acquisition agreements', threshold: 0.45, usage_count: 23, avg_confidence: 0.89 },
      { id: 'tag2', name: 'Due Diligence', description: 'Transaction due diligence materials', threshold: 0.45, usage_count: 18, avg_confidence: 0.85 },
      { id: 'tag3', name: 'Corporate Governance', description: 'Board and governance matters', threshold: 0.45, usage_count: 12, avg_confidence: 0.91 },
    ],
  },
  {
    id: 't2',
    name: 'Securities / Capital Markets',
    description: 'Securities filings, offerings, and capital markets',
    color: '#3b82f6',
    icon: 'TrendingUp',
    tag_count: 5,
    tags: [
      { id: 'tag4', name: 'SEC Filings', description: 'SEC and regulatory filings', threshold: 0.45, usage_count: 34, avg_confidence: 0.92 },
      { id: 'tag5', name: 'Financial Statements', description: 'Financial reports and statements', threshold: 0.45, usage_count: 28, avg_confidence: 0.88 },
      { id: 'tag6', name: 'Risk Factors', description: 'Risk disclosures and factors', threshold: 0.45, usage_count: 15, avg_confidence: 0.84 },
      { id: 'tag7', name: 'Management Discussion', description: 'MD&A and management analysis', threshold: 0.45, usage_count: 21, avg_confidence: 0.86 },
      { id: 'tag8', name: 'Executive Compensation', description: 'Executive pay and equity awards', threshold: 0.45, usage_count: 9, avg_confidence: 0.90 },
    ],
  },
  {
    id: 't3',
    name: 'Investment Funds',
    description: 'Private equity, venture capital, and investment funds',
    color: '#f59e0b',
    icon: 'Landmark',
    tag_count: 4,
    tags: [
      { id: 'tag9', name: 'Limited Partnership Agreement', description: 'LP and fund formation documents', threshold: 0.45, usage_count: 19, avg_confidence: 0.91 },
      { id: 'tag10', name: 'Capital Calls', description: 'Capital contributions and drawdowns', threshold: 0.45, usage_count: 14, avg_confidence: 0.87 },
      { id: 'tag11', name: 'Distribution', description: 'Fund distributions and waterfall', threshold: 0.45, usage_count: 11, avg_confidence: 0.89 },
      { id: 'tag12', name: 'Side Letter', description: 'Investor side letters and special terms', threshold: 0.45, usage_count: 8, avg_confidence: 0.85 },
    ],
  },
  {
    id: 't4',
    name: 'Litigation',
    description: 'Disputes, litigation, and settlements',
    color: '#ef4444',
    icon: 'Gavel',
    tag_count: 3,
    tags: [
      { id: 'tag13', name: 'Complaint / Pleading', description: 'Court filings and pleadings', threshold: 0.45, usage_count: 42, avg_confidence: 0.86 },
      { id: 'tag14', name: 'Settlement', description: 'Settlement agreements and releases', threshold: 0.45, usage_count: 31, avg_confidence: 0.90 },
      { id: 'tag15', name: 'Discovery', description: 'Discovery requests and responses', threshold: 0.45, usage_count: 27, avg_confidence: 0.83 },
    ],
  },
  {
    id: 't5',
    name: 'Real Estate',
    description: 'Real property transactions and leases',
    color: '#84cc16',
    icon: 'Home',
    tag_count: 3,
    tags: [
      { id: 'tag16', name: 'Purchase Agreement', description: 'Real property purchase and sale', threshold: 0.45, usage_count: 8, avg_confidence: 0.92 },
      { id: 'tag17', name: 'Lease Agreement', description: 'Commercial and residential leases', threshold: 0.45, usage_count: 15, avg_confidence: 0.89 },
      { id: 'tag18', name: 'Mortgage / Financing', description: 'Real estate financing documents', threshold: 0.45, usage_count: 6, avg_confidence: 0.87 },
    ],
  },
  {
    id: 't6',
    name: 'Employment',
    description: 'Employment and labor matters',
    color: '#06b6d4',
    icon: 'Users',
    tag_count: 3,
    tags: [
      { id: 'tag19', name: 'Employment Agreement', description: 'Employment contracts and offers', threshold: 0.45, usage_count: 24, avg_confidence: 0.93 },
      { id: 'tag20', name: 'Non-Compete / NDA', description: 'Restrictive covenants and confidentiality', threshold: 0.45, usage_count: 19, avg_confidence: 0.88 },
      { id: 'tag21', name: 'Benefits / ERISA', description: 'Employee benefits and retirement plans', threshold: 0.45, usage_count: 7, avg_confidence: 0.85 },
    ],
  },
]

export const demoProcessingTrends = [
  { date: '2025-12-20', processed: 45, failed: 2, avg_time: 2.1 },
  { date: '2025-12-21', processed: 38, failed: 1, avg_time: 2.3 },
  { date: '2025-12-22', processed: 52, failed: 3, avg_time: 2.0 },
  { date: '2025-12-23', processed: 29, failed: 0, avg_time: 2.4 },
  { date: '2025-12-24', processed: 18, failed: 1, avg_time: 2.2 },
  { date: '2025-12-25', processed: 8, failed: 0, avg_time: 2.5 },
  { date: '2025-12-26', processed: 41, failed: 1, avg_time: 2.1 },
]

export const demoModelUsage = [
  { model_name: 'pile-of-law/legalbert-large-1.7M-2', usage_count: 231, avg_time: 1.8 },
  { model_name: 'gemini-2.0-flash', usage_count: 89, avg_time: 3.2 },
  { model_name: 'surya-ocr', usage_count: 45, avg_time: 4.5 },
]

export const demoMatterTypes = [
  { matter_type: 'M&A / Corporate', count: 3, document_count: 78 },
  { matter_type: 'Litigation', count: 2, document_count: 91 },
  { matter_type: 'Investment Funds', count: 2, document_count: 42 },
  { matter_type: 'Securities / Capital Markets', count: 2, document_count: 54 },
  { matter_type: 'Real Estate', count: 2, document_count: 23 },
  { matter_type: 'Employment', count: 1, document_count: 12 },
]

export const demoTaxonomyScoreboard = demoTaxonomy.map(area => ({
  area_id: area.id,
  area_name: area.name,
  color: area.color,
  total_usages: area.tags.reduce((sum, t) => sum + t.usage_count, 0),
  avg_confidence: area.tags.reduce((sum, t) => sum + t.avg_confidence, 0) / area.tags.length,
  tag_count: area.tag_count,
}))

// Demo document with tags for detail view
export const demoDocumentDetail = {
  id: '101',
  filename: 'Merger_Agreement_Draft_v3.pdf',
  status: 'completed',
  matter_id: '1',
  matter_name: 'Acme Corp Acquisition',
  page_count: 45,
  word_count: 12450,
  uploaded_at: '2025-12-20T10:30:00Z',
  processed_at: '2025-12-20T10:32:15Z',
  processing_time: 2.25,
  tags: [
    { tag_name: 'Merger Agreement', confidence: 0.94, area_name: 'M&A / Corporate' },
    { tag_name: 'Due Diligence', confidence: 0.78, area_name: 'M&A / Corporate' },
    { tag_name: 'Corporate Governance', confidence: 0.65, area_name: 'M&A / Corporate' },
  ],
  text_preview: 'AGREEMENT AND PLAN OF MERGER\n\nThis Agreement and Plan of Merger (this "Agreement") is entered into as of December 15, 2025, by and among Acme Corporation, a Delaware corporation ("Parent"), Acme Merger Sub, Inc., a Delaware corporation and a wholly owned subsidiary of Parent ("Merger Sub"), and Target Company, Inc., a Delaware corporation (the "Company").\n\nRECITALS\n\nWHEREAS, the Board of Directors of each of Parent, Merger Sub and the Company has determined that it is in the best interests of their respective stockholders...',
}

export const demoMatterDetail = {
  ...demoMatters[0],
  documents: demoDocuments.filter(d => d.matter_id === '1'),
  top_tags: [
    { tag_name: 'Merger Agreement', count: 12, avg_confidence: 0.91 },
    { tag_name: 'Due Diligence', count: 8, avg_confidence: 0.85 },
    { tag_name: 'Corporate Governance', count: 5, avg_confidence: 0.88 },
  ],
}
